"""empty message

Revision ID: 65b601ecd827
Revises: 
Create Date: 2020-08-07 18:00:51.584217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b601ecd827'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_codes',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_index(op.f('ix_account_codes_account_name'), 'account_codes', ['account_name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=120), nullable=True),
    sa.Column('accounting_email', sa.String(length=120), nullable=False),
    sa.Column('use_taggun', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_accounting_email'), 'user', ['accounting_email'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.create_index(op.f('ix_user_use_taggun'), 'user', ['use_taggun'], unique=False)
    op.create_table('reclaim_forms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('made_by', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['made_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reclaim_forms_date_created'), 'reclaim_forms', ['date_created'], unique=False)
    op.create_index(op.f('ix_reclaim_forms_description'), 'reclaim_forms', ['description'], unique=False)
    op.create_index(op.f('ix_reclaim_forms_filename'), 'reclaim_forms', ['filename'], unique=False)
    op.create_index(op.f('ix_reclaim_forms_id'), 'reclaim_forms', ['id'], unique=False)
    op.create_index(op.f('ix_reclaim_forms_made_by'), 'reclaim_forms', ['made_by'], unique=False)
    op.create_index(op.f('ix_reclaim_forms_sent'), 'reclaim_forms', ['sent'], unique=False)
    op.create_table('reclaim_forms_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_receipt', sa.String(length=10), nullable=True),
    sa.Column('made_by', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('miles', sa.Float(), nullable=True),
    sa.Column('Total', sa.Float(), nullable=True),
    sa.Column('row_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('image_name', sa.String(length=60), nullable=True),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account_codes.account_id'], ),
    sa.ForeignKeyConstraint(['form_id'], ['reclaim_forms.id'], ),
    sa.ForeignKeyConstraint(['made_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reclaim_forms_details_account_id'), 'reclaim_forms_details', ['account_id'], unique=False)
    op.create_index(op.f('ix_reclaim_forms_details_date_receipt'), 'reclaim_forms_details', ['date_receipt'], unique=False)
    op.create_index(op.f('ix_reclaim_forms_details_description'), 'reclaim_forms_details', ['description'], unique=False)
    op.create_index(op.f('ix_reclaim_forms_details_form_id'), 'reclaim_forms_details', ['form_id'], unique=False)
    op.create_index(op.f('ix_reclaim_forms_details_image_name'), 'reclaim_forms_details', ['image_name'], unique=False)
    op.create_index(op.f('ix_reclaim_forms_details_made_by'), 'reclaim_forms_details', ['made_by'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reclaim_forms_details_made_by'), table_name='reclaim_forms_details')
    op.drop_index(op.f('ix_reclaim_forms_details_image_name'), table_name='reclaim_forms_details')
    op.drop_index(op.f('ix_reclaim_forms_details_form_id'), table_name='reclaim_forms_details')
    op.drop_index(op.f('ix_reclaim_forms_details_description'), table_name='reclaim_forms_details')
    op.drop_index(op.f('ix_reclaim_forms_details_date_receipt'), table_name='reclaim_forms_details')
    op.drop_index(op.f('ix_reclaim_forms_details_account_id'), table_name='reclaim_forms_details')
    op.drop_table('reclaim_forms_details')
    op.drop_index(op.f('ix_reclaim_forms_sent'), table_name='reclaim_forms')
    op.drop_index(op.f('ix_reclaim_forms_made_by'), table_name='reclaim_forms')
    op.drop_index(op.f('ix_reclaim_forms_id'), table_name='reclaim_forms')
    op.drop_index(op.f('ix_reclaim_forms_filename'), table_name='reclaim_forms')
    op.drop_index(op.f('ix_reclaim_forms_description'), table_name='reclaim_forms')
    op.drop_index(op.f('ix_reclaim_forms_date_created'), table_name='reclaim_forms')
    op.drop_table('reclaim_forms')
    op.drop_index(op.f('ix_user_use_taggun'), table_name='user')
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_accounting_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_account_codes_account_name'), table_name='account_codes')
    op.drop_table('account_codes')
    # ### end Alembic commands ###
